#ifndef RISCV_MCAUSE_H
#define RISCV_MCAUSE_H

#define MCAUSE_EXCEPTION_SHIFT 0
#define MCAUSE_INTERRUPT_SHIFT 31

#define MCAUSE_EXCEPTION_MASK 0xFFFFFFF1ull
#define MCAUSE_INTERRUPT_MASK 0x80000000ull

#endif /* RISCV_MCOUNTEREN_H */
