#ifndef RISCV_MEDELEG64_H
#define RISCV_MEDELEG64_H

#define MEDELEG64_SYNCHRONOUS_EXCEPTIONS_SHIFT 0

#define MEDELEG64_SYNCHRONOUS_EXCEPTIONS_MASK 0xFFFFFFFFFFFFFFFFull

#endif /* RISCV_MEDELEG64_H */
