#ifndef RISCV_MIDELEG64_H
#define RISCV_MIDELEG64_H

#define MIDELEG64_SYNCHRONOUS_EXCEPTIONS_SHIFT 0

#define MIDELEG64_SYNCHRONOUS_EXCEPTIONS_MASK 0xFFFFFFFFFFFFFFFFull

#endif /* RISCV_MIDELEG64_H */
