#ifndef RISCV_MISA_H
#define RISCV_MISA_H

#define MISA_EXTENTIONS_SHIFT 0
#define MISA_ZERO_SHIFT 26
#define MISA_MXL_SHIFT 30

#define MISA_EXTENTIONS_MASK 0x01FFFFFFull
#define MISA_ZERO_MASK 0x00000000ull
#define MISA_MXL_MASK 0x10000000ull

#endif /* RISCV_MISA_H */
