#ifndef RISCV_MSTATUSH_H
#define RISCV_MSTATUSH_H

#define MSTATUSH_SBE_SHIFT 4
#define MSTATUSH_MBE_SHIFT 5

#define MSTATUSH_SBE_MASK 0x0000 0010ull
#define MSTATUSH_MBE_MASK 0x0000 0020ull

#endif

