#ifndef RISCV_MTVEC_H
#define RISCV_MTVEC_H

#define MTVEC_MODE_DIRECT_SHIFT   0
#define MTVEC_MODE_VECTORED_SHIFT 0
#define MTVEC_BASE_SHIFT          2

#define MTVEC_MODE_DIRECT_MASK   0x00000003ull
#define MTVEC_MODE_VECTORED_MASK 0x00000003ull
#define MTVEC_BASE_MASK          0xFFFFFFFCull

#endif /* RISCV_MTVEC_H */
