#ifndef RISCV_STVEC_H
#define RISCV_STVEC_H

#define STVEC_MODE_SHIFT 0
#define STVEC_BASE_SHIFT 2

#define STVEC_MODE_MASK 0x0000000000000003ull
#define STVEC_BASE_MASK 0xFFFFFFFFFFFFFFFCull

#define STVEC_MODE_DIRECT   0
#define STVEC_MODE_VECTORED 1

#endif /* RISCV_STVEC_H */
