#ifndef RISCV_STVEC_H
#define RISCV_STVEC_H

#define STVEC_MODE_DIRECT_SHIFT   0
#define STVEC_MODE_VECTORED_SHIFT 0
#define STVEC_BASE_SHIFT          2

#define STVEC_MODE_DIRECT_MASK   0x00000003ull
#define STVEC_MODE_VECTORED_MASK 0x00000003ull
#define STVEC_BASE_MASK          0xFFFFFFFCull

#endif /* RISCV_STVEC_H */
